### ISSUE TITLE
WS-2020-0408 - High Severity Vulnerability

### ISSUE THREAD

**Issue by vamshivishnu** [strongdm/strongdm-sdk-java#4]
Vulnerable Library - netty-handler-4.1.67.Final.jar
 Library home page: https://netty.io/

Path to dependency file: /pom.xml

Path to vulnerable library: /home/wss-scanner/.m2/repository/io/netty/netty-handler/4.1.67.Final/netty-handler-4.1.67.Final.jar

Dependency Hierarchy:

strongdm-sdk-java-3.4.0.jar (Root Library)
grpc-netty-1.42.2.jar
netty-codec-http2-4.1.67.Final.jar
❌ netty-handler-4.1.67.Final.jar (Vulnerable Library)

Vulnerability Details

An issue was found in all versions of io.netty:netty-all. Host verification in Netty is disabled by default. This can lead to MITM attack in which an attacker can forge valid SSL/TLS certificates for a different hostname in order to intercept traffic that doesn’t intend for him. This is an issue because the certificate is not matched with the host.

Publish Date: 2020-06-22

URL: [WS-2020-0408](https://github.com/netty/netty/issues/10362)

CVSS 2 Score Details (7.4)

Fix Resolution: io.netty:netty-all - 4.1.68.Final-redhat-00001,4.0.0.Final,4.1.67.Final-redhat-00002;io.netty:netty-handler - 4.1.68.Final-redhat-00001,4.1.67.Final-redhat-00001

**Comment by mdube667** [comment]
@vamshivishnu Thank you for letting us know. We're tracking a fix for this internally.

**Comment by jarindykstra** [comment]
@vamshivishnu This has been updated in latest version of the SDK

**Comment by 200sc** [comment]
Resolved since v3.5.2
